CREATE TABLE IF NOT EXISTS users(
id BIGINT AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL,
password VARCHAR(8) NOT NULL,
active BOOLEAN NOT NULL,
first_name VARCHAR(255) NOT NULL,
last_name VARCHAR(255) NOT NULL,
age integer NOT NULL ,
gender VARCHAR(1000)  NOT NULL,
marital_status VARCHAR(1000) NOT NULL,
address VARCHAR(1000) NOT NULL,
city VARCHAR(1000) NOT NULL,
state VARCHAR(1000) NOT NULL,
country VARCHAR(1000) NOT NULL,
contact_no_1 VARCHAR(15) NOT NULL,
contact_no_2 VARCHAR(15),
employee_code VARCHAR(50) NOT NULL,
official_address VARCHAR(1000) NOT NULL,
official_city VARCHAR(1000) NOT NULL,
official_state VARCHAR(1000) NOT NULL,
official_country VARCHAR(1000) NOT NULL,
company_contact_no VARCHAR(15) NOT NULL,
company_contact_email VARCHAR(255) NOT NULL,
company_name VARCHAR(255) NOT NULL,
CHECK(age > 0)
)
